.github/workflows/e2e-test.yaml, README.md, core/src/main/java/com/sap/ai/sdk/core/Core.java, core/src/test/java/com/sap/ai/sdk/core/CoreTest.java
Environment variables should be uppercase.
=> Changed service key env var to `AICORE_SERVICE_KEY`

core/src/main/java/com/sap/ai/sdk/core/Core.java, core/src/test/java/com/sap/ai/sdk/core/CoreTest.java
AI/ai-sdk-java-backlog#61.
Test to be added with AI/ai-sdk-java-backlog#63
=> feat: Add Metering Header

e2e-test-app/src/test/java/com/sap/ai/sdk/app/controllers/OpenAiTest.java, foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/StreamedDelta.java
Change due to addition of token usage
=> Fix E2E Test

.github/ISSUE_TEMPLATE/sdk-issue.md
AI/ai-sdk-java-backlog#76.
Our customers need a template to create high quality issues
=> Create issue template

.github/dependabot.yaml, .github/workflows/dependabot-automerge.yaml
AI/ai-sdk-java-backlog#67.
ependabot pull requests appear every week, They should be auto-merged if they are green to save time.
=> Dependabot automerge

core/src/main/java/com/sap/ai/sdk/core/AiCoreDestination.java, core/src/main/java/com/sap/ai/sdk/core/AiCoreService.java, core/src/main/java/com/sap/ai/sdk/core/DeploymentCache.java, core/src/main/java/com/sap/ai/sdk/core/DestinationResolver.java, core/src/test/java/com/sap/ai/sdk/core/AiCoreServiceTest.java, core/src/test/java/com/sap/ai/sdk/core/CacheTest.java, core/src/test/java/com/sap/ai/sdk/core/DestinationResolverTest.java, core/src/test/java/com/sap/ai/sdk/core/client/ArtifactUnitTest.java, core/src/test/java/com/sap/ai/sdk/core/client/ConfigurationUnitTest.java, core/src/test/java/com/sap/ai/sdk/core/client/DeploymentUnitTest.java, core/src/test/java/com/sap/ai/sdk/core/client/ExecutionUnitTest.java, core/src/test/java/com/sap/ai/sdk/core/client/ScenarioUnitTest.java, core/src/test/java/com/sap/ai/sdk/core/client/WireMockTestServer.java, core/src/test/resources/__files/GPT4DeploymentResponse.json, core/src/test/resources/__files/emptyDeploymentResponse.json
* Generated code does not apply
=> Lombok use of `val`

.pipeline/checkstyle-suppressions.xml, pom.xml
=> Make checkstyle fail on info-level findings

core/src/main/java/com/sap/ai/sdk/core/AiCoreService.java
AI/ai-sdk-java-backlog#57.
[Context](https://github.com/SAP/ai-sdk-java/pull/129#pullrequestreview-2409878900)
=> Performance fix: Made `Dotenv.load()` static

sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java, sample-code/spring-app/src/main/resources/static/index.html, sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java
=> Charles review

core/src/main/java/com/sap/ai/sdk/core/DeploymentCache.java, core/src/test/java/com/sap/ai/sdk/core/CacheTest.java, core/src/test/java/com/sap/ai/sdk/core/client/DeploymentUnitTest.java, core/src/test/resources/__files/GPT4DeploymentResponse.json, docs/guides/OPENAI_CHAT_COMPLETION.md
AI/ai-sdk-java-backlog#16.
The workaround is no longer needed.
=> chore: Remove Backend_details workaround

README.md
~AI/ai-sdk-java-backlog#ISSUENUMBER.~
(no issue number)
Update the readme to fix navigation information in part "Set AI Core Credentials".
(not applicable)
(not applicable)
=> Update README.md: Fix Navigation in "Set AI Core Credentials"

.github/workflows/perform-release.yml, pom.xml
=> fix: [DevOps] Release Script

sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java
Overlooked this when implementing #191
=> fix: [DevOps] Fix Masking E2E Test

.github/workflows/e2e-test.yaml, sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java, sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java
This PR adds the capability to E2E test against multiple AI Core landscapes using test toggles.
=> chore: [DevOps] E2E Test Matrix Build

core/pom.xml, foundation-models/openai/pom.xml, orchestration/pom.xml, pom.xml, sample-code/spring-app/pom.xml
AI/ai-sdk-java-backlog#78.
[Pom descriptions are public](https://mvnrepository.com/artifact/com.sap.ai.sdk), We should mention that they are official `SAP Cloud SDK for AI`.
Pom names are only for terminal logs
=> chore: improve maven pom descriptions

docs/adrs/005-release-strategy.md
This PR adds an ADR on how the development lifecycle of the AI SDK lines up with development of the AI Core service.
=> [DevOps] ADR005: Development Lifecycle

core/src/main/java/com/sap/ai/sdk/core/AiCoreService.java, core/src/test/java/com/sap/ai/sdk/core/AiCoreServiceTest.java, foundation-models/openai/pom.xml, foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiClient.java, orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationClient.java
Adding a Builder for better readability to #201
=> Refactor Core Classes with Builder

.github/workflows/fosstars-report.yml, pom.xml
Uses https://cveb.in/ instead, see also the discussion [here](https://github.com/jeremylong/DependencyCheck/issues/7180#issuecomment-2500914164)
=> chore: [DevOps] Switch to Mirror for CVE Downloads

.github/workflows/continuous-integration.yaml, .github/workflows/e2e-test.yaml, .github/workflows/fosstars-report.yml
Required after Dependabot updated the major version of the action to 2.0.0
=> chore: [DevOps] Fix Slack Notifications

.github/workflows/fosstars-report.yml
Running this from a branch removed the cache from the main branch 🙄
=> Fix CVE Scan again

docs/guides/OPENAI_CHAT_COMPLETION.md
=> Added embedding documentation

docs/guides/ORCHESTRATION_CHAT_COMPLETION.md
=> Fix: Update Table of Contents

docs/release-notes/release_notes.md
=> Missing release notes

README.md, docs/guides/AI_CORE_DEPLOYMENT.md, docs/guides/CONNECTING_TO_AICORE.md, sample-code/spring-app/README.md
Minor updates based on user feedback.
=> chore: [Documentation] Add Disclaimer for Model Classes and Improve Connectivity Guide

.github/workflows/continuous-integration.yaml, .github/workflows/spec-update.yaml
Automation to update spec files.
Features:
- One job to rule them all
- Supports spec version based on tag or branch
- Can be triggered from outside this repo as well
- Creating a PR is optional, which is useful for testing
=> chore: [DevOps] Automation to Update Spec Files

.github/workflows/spec-update.yaml
AI/ai-sdk-java-backlog#114
Cosmetic changes & aligning with the JS variant
=> chore: [DevOps] Minor Spec Update Job Improvements

docs/release-notes/release_notes.md
Add release notes for: https://github.com/SAP/ai-sdk-java/pull/280
=> feat: Update model list for orchestration

.github/workflows/prepare-release.yaml
Fix small error in a link in the PR message of `prepare-release.yaml`.
=> fix: Fix link in PR message of prepare-release.yaml

README.md, docs/guides/SPRING_AI_INTEGRATION.md, docs/release-notes/release_notes.md
AI/ai-sdk-java-backlog#165.
Release notes were forgotten + drive-by fixes
=> fix: Update docs

foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiModel.java, sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/ScenarioTest.java
Related https://github.com/SAP/ai-sdk-java/pull/349
=> chore: Enable E2E test for OpenAI models

docs/guides/SPRING_AI_INTEGRATION.md, docs/release-notes/release_notes.md, orchestration/pom.xml, orchestration/src/main/java/com/sap/ai/sdk/orchestration/spring/OrchestrationChatModel.java, orchestration/src/test/java/com/sap/ai/sdk/orchestration/spring/OrchestrationChatModelTest.java, orchestration/src/test/resources/chatMemory.json, sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/SpringAiOrchestrationController.java, sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/SpringAiOrchestrationService.java, sample-code/spring-app/src/main/resources/static/index.html, sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/SpringAiOrchestrationTest.java
AI/ai-sdk-java-backlog#174.
The Spring AI integration did not support chat memory
=> feat: [Orchestration] Chat Memory

docs/guides/ORCHESTRATION_CHAT_COMPLETION.md, sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/OrchestrationService.java
Fixed some small things in `OrchestrationService` and in `ORCHESTRATION_CHAT_COMPLETION.md`.
=> docs: Small fixes to sample code and docs

sample-code/spring-app/pom.xml
AI/ai-sdk-java-backlog#ISSUENUMBER.
This PR updates the Spring version to address a transitive dependency vulnerability in `tomcat-embed-core`. The update fixes the CVE-2025-24813 vulnerability identified in the OWASP Dependency Check.
=> fix: [DevOps] Update spring boot version

sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java, sample-code/spring-app/src/main/resources/static/index.html
The orchestration container was too big, now every item is collapsed but the first one.
=> fix: HTML homepage collapse

sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/OrchestrationService.java, sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/SpringAiOrchestrationService.java, sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/SpringAiOrchestrationTest.java
=> feat: [Orchestration] Add Test and Sample Code for Response Format with Spring AI

.github/workflows/spec-update.yaml
AI/ai-sdk-java-backlog#261.
The spec update script cannot update document grounding
Successful PR: https://github.com/SAP/ai-sdk-java/pull/433
=> feat: [DevOps] Document Grounding spec update script

docs/release_notes.md, orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationAiModel.java
AI/ai-sdk-java-backlog#265.
Added DeepSeek-R1 model
=> feat: [Orchestration] Added DeepSeek-R1 model

docs/release_notes.md
AI/ai-sdk-java-backlog#216
Add tool execution to release notes
=> chore: [Orchestration] Add tool execution to release notes

sample-code/spring-app/pom.xml
Fixes https://nvd.nist.gov/vuln/detail/CVE-2025-31651 and https://nvd.nist.gov/vuln/detail/CVE-2025-31650
[Successful vulnerability scan](https://github.com/SAP/ai-sdk-java/actions/runs/14900647762)
=> feat: [DevOps] Update spring-boot to 3.4.5

sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java
AI/ai-sdk-java-backlog#236.
Add some tests to check that during streaming orchestration errors are handled correctly.
=> chore: [Orchestration] Test streaming error handling

.github/workflows/weekly-spec-update.yaml
AI/ai-sdk-java-backlog#235.
A PR is created for updating spec and clients automatically, when needed, via a weekly job.
_Orchestration is not included because we need a version number_
[successful run](https://github.com/CharlesDuboisSAP/ai-sdk-java/actions/runs/15016132663)
=> feat: [DevOps] Weekly Spec Update

docs/release_notes.md, foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiModel.java
Update available models list for OpenAI models.
**Note:** The new models are not yet listed in the [SAP note](https://me.sap.com/notes/3437766).
=> fix: [OpenAI] Update models list of OpenAI models.

docs/release_notes.md, orchestration/src/main/java/com/sap/ai/sdk/orchestration/ConfigToRequestTransformer.java, orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationModuleConfig.java, sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java, sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/OrchestrationService.java, sample-code/spring-app/src/main/resources/static/index.html, sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java
AI/ai-sdk-java-backlog#259.
The orchestration translation module was generated last week. This an e2e test
Fix for error 500 https://github.tools.sap/AI/llm-orchestration/issues/1394
=> feat: [Orchestration] Translation

.github/workflows/e2e-test.yaml, sample-code/spring-app/pom.xml
- [link](https://github.com/SAP/ai-sdk-java/actions/runs/15917805788/job/44898590661) to fosstar failure one main (before this fix)
- [link](https://github.com/SAP/ai-sdk-java/actions/runs/15927881032) to successful run on this branch
=> chore: Update apache tomcat version because of CVE-2025-48988

.github/workflows/spec-update.yaml
Follow up to #483, switching directly to v2
=> ci: Update spec-update.yaml

core/src/main/java/com/sap/ai/sdk/core/common/ClientResponseHandler.java, core/src/main/java/com/sap/ai/sdk/core/common/ClientStreamingHandler.java, core/src/main/java/com/sap/ai/sdk/core/common/IterableStreamConverter.java, docs/release_notes.md, orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationHttpExecutor.java
- error messages updated and cut error object logging
AI/ai-sdk-java-backlog#290.
We want to avoid exposing any sensitive information via logs. The changes contained removes any response/request body being logged.
Additional, logging of suspicious error objects have been removed. Error messages are also carefully checked to contain sanitized information.
=> fix: [Core] Remove any logging of response request body

.github/ISSUE_TEMPLATE/bug-report.yml
This PR fixes the "Dependency tree via `mvn dependency:tree`" part of the bug-report template.
- related PR for Cloud SDK: https://github.com/SAP/cloud-sdk-java/pull/867
=> fix: Fix `dependency tree` field in bug-report.yml

.github/workflows/continuous-integration.yaml, .github/workflows/dependency-test.yaml, .github/workflows/deploy-snapshot.yaml, .github/workflows/e2e-test.yaml, .github/workflows/fosstars-report.yml, .github/workflows/prepare-release.yaml, .github/workflows/weekly-spec-update.yaml
https://github.com/SAP/ai-sdk-java/security/code-scanning
Added permissions and reduced secret scope
=> fix: [DevOps] CodeQL Security findings
