SAP/ai-sdk-java

docs/adrs/002-testing-strategy.md

Document our testing strategy.

chore: [ADR] Testing Strategy

---

docs/adrs/003-code-generation.md

WiP ADR on how we generate which parts of our code base from OpenAPI spec files

chore [ADR] Code Generation

---

.github/workflows/fosstars-report.yml
README.md

AI/ai-sdk-java-backlog#46.
Fosstars are needed for compliance reasons.

Added Fosstars

---

README.md
core/src/main/java/com/sap/ai/sdk/core/Core.java
e2e-test-app/src/main/java/com/sap/ai/sdk/app/controllers/DeploymentController.java

AI/ai-sdk-java-backlog#53.
Follow up of #4, especially: Fix return type `@Nonnull` / `@Nullable` annotation.
Now that the return type is `@Nonnull`, we can remove requireNonNull.

Remove requireNonNull

---

.github/workflows/continuous-integration.yaml
README.md

continuous integration needs to run on main, plus the badge should only show if the main branch succeeds.
Currently the badge shows the latest pull request status.

Enable CI on main

---

README.md

AI/ai-sdk-java-backlog#56.
Explain options:
* Regular service binding in SAP BTP Cloud Foundry (resulting in `VCAP_SERVICES` env var entry).
* Set an environment variable explicitly: `AICORE_SERVICE_KEY`
* Define and use a _Destination_ in _BTP Destination Service_.
* ~Leveraging `"user-provided"` service binding (currently not recommended).~
* ~Define and use a custom `ServiceBinding` or `ServiceBindingAccessor` declaration in application (not recommended).~
I chose to enhance the `README.md` (instead of starting a new `docs/` document).

doc: Add explanation for service binding options

---

core/src/main/java/com/sap/ai/sdk/core/Core.java

See https://github.wdf.sap.corp/AI/apis/issues/79

Add Workaround for backend_details change

---

.github/workflows/perform-release.yml
pom.xml
sample-code/spring-app/pom.xml

I think it would be safer to exclude the whole sub-module when deploying.
For that we would change the cli usage from `P` profile to `-D` system arg.

[Re: Added release script] Potential simplification

---

foundation-models/openai/src/test/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiClientTest.java
foundation-models/openai/src/test/resources/chatCompletionResponse.json

AI/ai-sdk-java-backlog#66.
Updated the outdated unit test payload for OpenAI.

Update OpenAI test payload

---

.github/workflows/continuous-integration.yaml

We forgot to enable the Slack notification on continuous integration when we enabled the workflow on main

Notify when main branch fails

---

.github/workflows/continuous-integration.yaml
.github/workflows/dependabot-automerge.yaml

The `dependabot-automerge.yaml` workflow did not merge all dependabot PRs. I suspect this is a timing issue. I added one hour.

Dependabot Auto-Merge fix

---

core/src/main/java/com/sap/ai/sdk/core/AiCoreService.java
core/src/main/java/com/sap/ai/sdk/core/DeploymentCache.java
core/src/test/java/com/sap/ai/sdk/core/CacheTest.java
core/src/test/resources/__files/GPT4DeploymentResponse.json
core/src/test/resources/__files/emptyDeploymentResponse.json

AI/ai-sdk-java-backlog#54.
The deployment cache needs to isolate between resource groups.
Also customers should be able to reset the cache

Added resource group isolation to DeploymentCache

---

pom.xml

Sample output:
```
mvn clean install -f core
[...]
[INFO] 
[INFO] --- spotbugs:4.8.6.4:check (default) @ core ---
[INFO] BugInstance size is 2
[INFO] Error size is 0
[INFO] Total bugs: 2
[ERROR] High: com.sap.ai.sdk.core.client.model.AiDeployment$LastOperationEnum.fromValue(String) may return null, but is declared @Nonnull [com.sap.ai.sdk.core.client.model.AiDeployment$LastOperationEnum] At AiDeployment.java:[line 181] NP_NONNULL_RETURN_VIOLATION
[ERROR] High: com.sap.ai.sdk.core.client.model.AiDeploymentResponseWithDetails$LastOperationEnum.fromValue(String) may return null, but is declared @Nonnull [com.sap.ai.sdk.core.client.model.AiDeploymentResponseWithDetails$LastOperationEnum] At AiDeploymentResponseWithDetails.java:[line 181] NP_NONNULL_RETURN_VIOLATION
[INFO] 
To see bug detail …
```

Run Spotbugs by default

---

.pipeline/checkstyle-suppressions.xml
.pipeline/config.yml
pom.xml

Sample output:
```
mvn clean install -f foundationmodels/openai
[...]
[INFO] 
[INFO] --- checkstyle:3.5.0:check (default) @ openai ---
[INFO] There are 3 errors reported by Checkstyle 10.18.2 with C:\SAPDevelop\ai-sdk-java\foundation-models\openai/../..//.pipeline/checkstyle.xml ruleset.
[ERROR] src\main\java\com\sap\ai\sdk\foundationmodels\openai\model\OpenAiChatCompletionParameters.java:[95,39] (misc) TodoComment: Comment matches to-do format '(TODO)|(todo)|(ToDo)|(FIXME)|(fixme)|(FixMe)'.
[ERROR] src\main\java\com\sap\ai\sdk\foundationmodels\openai\model\OpenAiChatMessage.java:[255,7] (misc) TodoComment: Comment matches to-do format '(TODO)|(todo)|(ToDo)|(FIXME)|(fixme)|(FixMe)'.
[ERROR] src\main\java\com\sap\ai\sdk\foundationmodels\openai\model\OpenAiChatMessage.java:[271,11] (misc) …
```

Run Checkstyle by default

---

README.md
sample-code/spring-app/README.md

AI/ai-sdk-java-backlog#57.
The README had mistakes and was unclear in regards to AI Core service binding from a local machine

README fix for AICORE_SERVICE_KEY instructions

---

core/src/main/java/com/sap/ai/sdk/core/AiCoreService.java

Exposing this field publicly leads to some risks:
* User expects API stability
* .. for a field with a third-party class
* Implicit invitation for more util fields (feature creep)
* Auto-completion may confuse the user

Reduce visibility AiCoreService#DOTENV from public to private

---

README.md
docs/guides/ORCHESTRATION_CHAT_COMPLETION.md
orchestration/src/main/java/com/sap/ai/sdk/orchestration/ConfigToRequestTransformer.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/ModuleConfigFactory.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationClient.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationModuleConfig.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationPrompt.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/ConfigToRequestTransformerTest.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/ModuleConfigFactoryTest.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/OrchestrationUnitTest.java
pom.xml
sample-code/spring-app/README.md
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java
sample-code/spring-app/src/main/resources/static/index.html
sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java

AI/ai-sdk-java-backlog#55.
This PR introduces `OrchestrationPrompt` to allow for more convenient orchestration usage.
Soft prerequisite: #141 
Before:
```java
LLMModuleConfig llmConfig;
ChatMessage userMessage;
var template = TemplatingModuleConfig.create().template(userMessage);
var config = ModuleConfigs.create().llmModuleConfig(llmConfig).templatingModuleConfig(template);
var request =
CompletionPostRequest.create()
.orchestrationConfig(OrchestrationConfig.create().moduleConfigurations(config));
new OrchestrationClient().chatCompletion(request);
```
After:
```java
LLMModuleConfig llmConfig;
ChatMessage userMessage;
var prompt = new OrchestrationPrompt(userMessage);
var config = new OrchestrationModuleConfig().withLlmConfig(llmConfig);
new OrchestrationClient().chatCompletion(prompt, …
```

feat: Orchestration Prompt

---

.pipeline/sdk_specific_pmd_rules.xml

We should apply the same quality standards to `protected` API as we have for `public` API.
(Effective) protected API describes methods on public classes, that are reserved for overriding and reusing in extending classes.

[PMD] Apply public API rules to protected as well

---

.github/workflows/e2e-test.yaml

Shift the time to not run at the same time as JS

chore: [DevOps] Reschedule E2E Tests

---

docs/guides/ORCHESTRATION_CHAT_COMPLETION.md
orchestration/src/main/java/com/sap/ai/sdk/orchestration/DpiMasking.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/DpiMaskingConfig.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/MaskingProvider.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationModuleConfig.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/ConfigToRequestTransformerTest.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/OrchestrationUnitTest.java
pom.xml
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java

AI/ai-sdk-java-backlog#102.
As an orchestration user, I want to have a convenient way of configuring data masking.

Data Masking Convenience

---

docs/guides/ORCHESTRATION_CHAT_COMPLETION.md
orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationAiModel.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/OrchestrationModuleConfigTest.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/OrchestrationUnitTest.java

Follow up #152
I think we could drop the "model" prefix from the public methods, since the class already has the "model" reference in name.

Drop redundant "model" method prefix

---

foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiChatCompletionOutput.java

This PR aligns the handling of empty choices (which should never occur) in the `OpenAiChatResponseOutput` class with the behaviour discussed in https://github.com/SAP/ai-sdk-java/pull/173.

Align handling of empty choices

---

.github/workflows/fosstars-report.yml
.github/workflows/update-vulnerability-database.yaml

This PR adds a cache for OWASP entries.

chore: [DevOps] OWASP Cache

---

docs/guides/ORCHESTRATION_CHAT_COMPLETION.md
orchestration/src/main/java/com/sap/ai/sdk/orchestration/Message.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationChatResponse.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/OrchestrationUnitTest.java
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java
sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java

- Mark content getter beta
- Improve e2e test for continuous message interaction.
AI/ai-sdk-java-backlog#101.
Users should be able to directly plugin the response messages as part of message history for  subsequent prompts.

[Orchestration] Convenience Message on Response

---

sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java

(Very minor)
Seems like one of the javadocs in the sample-code git simply copied to another method.
n.a.
n.a.

Fix javadoc in sample code

---

.pipeline/checkstyle-suppressions.xml
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiChatCompletionChoice.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiChatCompletionDelta.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiChatCompletionFunction.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiChatCompletionOutput.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiChatCompletionParameters.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiChatCompletionTool.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiChatFunctionCall.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiChatMessage.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiChatToolCall.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiCompletionChoice.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiCompletionOutput.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiCompletionParameters.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiContentFilterDetectedResult.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiContentFilterPromptResults.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiContentFilterResultBase.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiContentFilterResultsBase.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiContentFilterSeverityResult.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiDeltaChatCompletionChoice.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiEmbeddingData.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiEmbeddingOutput.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiEmbeddingParameters.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiError.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiErrorBase.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiPromptFilterResult.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiUsage.java

* We decided to not employ the OpenAI spec changes of [2024-06-01](https://github.com/SAP/ai-sdk-java/pull/215) nor [2024-10-21](https://github.com/SAP/ai-sdk-java/pull/220), because the process for hand-written code is error-prone and partially untestable. Instead we will still with `2024-02-01`.
* We decided to keep the option open to migrate from hand-written code to generated code. This will be a breaking change.
* To mark API as unstable we will use `@Beta` on the hand-written model classes. For now. This is unfortunate for the user but reflects correctly on our API stability. Let's not give false promises.

Add `@Beta` annotation to OpenAI model classes

---

.github/workflows/fosstars-report.yml
pom.xml

Finally fixed: https://github.com/SAP/ai-sdk-java/actions/runs/12175714381/job/33962633080

Try fix CVE scan

---

orchestration/src/main/java/com/sap/ai/sdk/orchestration/JacksonMixins.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationClient.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/model/DataRepositoryType.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/model/FilterConfig.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/model/GroundingModuleConfigConfigFiltersInner.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/model/LLMModuleResult.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/model/MaskingProviderConfig.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/model/ModuleResultsOutputUnmaskingInner.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/model/TemplateRefTemplateRef.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/model/TemplatingModuleConfig.java

Applies [these changes](https://github.com/SAP/cloud-sdk-java/pull/657)

Update with new generator version

---

sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java
sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java

Our end-to-end tests started failing because we hit the OpenAI rate limit. To circumvent this, this PR switches the AI used for `OrchestrationTest` to `Gemini 1.5 flash`.

Exchanged GPT-3.5 for Gemini-1.5 in OrchestrationTest

---

sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/OrchestrationService.java

Gemini consistently refuses to generate enough numbers, and with the default chunk size of 100 barely any streaming occurs. The new prompt is more reliable

chore: [Orchestration] Improve Streaming Sample Code

---

sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OpenAiController.java
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/OpenAiService.java
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/OrchestrationService.java
sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OpenAiTest.java

AI/ai-sdk-java-backlog#132
Before, in the sample app we simply returned our Java classes in the controller and let them be deserialised to be displayed. This stopped working properly at some point for the `Orchestration` endpoints (see linked issue above). In order to circumvent this, we decided to not rely on the deserialisation and also split up the business logic of the app into a dedicated service class.
This PR does this for the `OpenAiController`.
There is a [related PR](https://github.com/SAP/ai-sdk-java/pull/240) (that is already merged) for `OrchestrationController`.

Refactor OpenAiController in sample app 

---

core/pom.xml
core/src/main/java/com/sap/ai/sdk/core/model/InlineObject.java
core/src/main/java/com/sap/ai/sdk/core/model/InlineObject1.java
core/src/main/java/com/sap/ai/sdk/core/model/InlineObject2.java
core/src/main/java/com/sap/ai/sdk/core/model/InlineObject3.java
core/src/main/java/com/sap/ai/sdk/core/model/InlineObject4.java
orchestration/pom.xml
pom.xml

Also re-enables the generators 🥳

chore: [DevOps] Update to Cloud SDK 5.15.0

---

orchestration/src/test/java/com/sap/ai/sdk/orchestration/OrchestrationUnitTest.java
orchestration/src/test/resources/filteringLooseRequest.json
orchestration/src/test/resources/maskingRequest.json
orchestration/src/test/resources/messagesHistoryRequest.json
orchestration/src/test/resources/templatingRequest.json

Test coverage of the methods in the `Orchestration` client was slightly below 85%. 
To increase test coverage I added the two previously untested parameters of the `OrchestrationAiModel` class to the test instance.

Increase Test Coverage for Orchestration

---

orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationChatResponse.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/OrchestrationUnitTest.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/PolymorphicFallbackDeserializerTest.java
orchestration/src/test/resources/__files/multiChatMessageResponse.json
orchestration/src/test/resources/__files/templatingResponse.json
orchestration/src/test/resources/multiChatMessageRequest.json

AI/ai-sdk-java-backlog#135.
Add all necessary test for new Orchestration update (12a)

Orchestration spec update 12a - Tests

---

docs/guides/AI_CORE_DEPLOYMENT.md
docs/guides/OPENAI_CHAT_COMPLETION.md

To improve focus, I think it's worth to only explicitly declare the "interesting" result types.
We did this in other parts of the docs already.
Not a strong opinion, I'm fine with using this PR as discussion starter.

[Doc] For request/parameter objects, use `var` instead of type

---

orchestration/src/main/java/com/sap/ai/sdk/orchestration/PolymorphicFallbackDeserializer.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/PolymorphicFallbackDeserializerTest.java

AI/ai-sdk-java-backlog#135.
Extend the test coverage for newly added generic deserialiser.

test: [Orchestration] Success scenarios for `PolymorphicFallbackDeserializer`

---

.github/workflows/pr-lint.yaml
.github/workflows/prepare-release.yaml

Examples which are allowed:
* `chore: [DevOps] PR Title Linter`
* `chore: [DevOps] pr title linter`
* `chore: PR Title Linter`
Examples which are not allowed:
* `PR Title Linter`
* `[DevOps] PR Title Linter`
* `chore: [Foo] PR Title Linter`
[Tested on my fork](https://github.com/MatKuhr/ai-sdk-java/actions/runs/12743754869/job/35514342688?pr=2)

chore: [DevOps] PR Title Linter

---

orchestration/src/test/java/com/sap/ai/sdk/orchestration/OrchestrationUnitTest.java
orchestration/src/test/resources/__files/groundingResponse.json
orchestration/src/test/resources/groundingRequest.json

AI/ai-sdk-java-backlog#144.
Extend the unit test for covering the request serialisation as well.

test: [Orchestration] Extend Grounding Unit Test

---

.github/workflows/continuous-integration.yaml
.github/workflows/dependency-test.yaml
.github/workflows/deploy-snapshot.yaml
.github/workflows/e2e-test.yaml
.github/workflows/fosstars-report.yml
.github/workflows/prepare-release.yaml

Hi Colleagues,
In .github/workflows/perform-release.yaml SapMachine is already used.
Created a PR to migrate the remaining GHA from Temurin to [SapMachine](https://sapmachine.io).
Regards Christian@SapMachine Team
PS: If possible consider to migrate to SapMachine 21 (LTS).

chore: [DevOps] Switch From Temurin to SapMachine

---

docs/guides/SPRING_AI_INTEGRATION.md

fix: Add Spring AI Dependency Requirements to the Docs

---

docs/guides/SPRING_AI_INTEGRATION.md
orchestration/pom.xml
orchestration/src/main/java/com/sap/ai/sdk/orchestration/spring/OrchestrationChatModel.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/spring/OrchestrationSpringChatDelta.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/spring/OrchestrationChatDeltaTest.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/spring/OrchestrationChatModelTest.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/spring/OrchestrationChatResponseTest.java
pom.xml
sample-code/spring-app/pom.xml
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/SpringAiOrchestrationController.java
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/OrchestrationService.java
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/SpringAiOrchestrationService.java
sample-code/spring-app/src/main/resources/static/index.html
sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/SpringAiOrchestrationTest.java

AI/ai-sdk-java-backlog#173.
The Spring AI client `OrchestrationChatModel` should have streaming support

feat: Spring AI Orchestration streaming

---

docs/guides/ORCHESTRATION_CHAT_COMPLETION.md
docs/release-notes/release_notes.md
orchestration/src/main/java/com/sap/ai/sdk/orchestration/Grounding.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/GroundingProvider.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/MaskingProvider.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationModuleConfig.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/OrchestrationModuleConfigTest.java
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/OrchestrationService.java

AI/ai-sdk-java-backlog#167.
TheGrounding configuration is full of boilerplate code. I added a layer of convenience.

feat: Orchestration Grounding convenience

---

orchestration/src/main/java/com/sap/ai/sdk/orchestration/spring/OrchestrationChatModel.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/spring/OrchestrationChatModelTest.java

Spring AI stream should be consistent with `streamChatCompletionDeltas()` which does not throw and return a stream of Deltas
Only `streamChatCompletion()` throws because it returns a stream of String, and the user cannot parse the content filter themselves

fix: Spring AI consistent behaviour with Orchestration streaming

---

pom.xml

Updated the JSON version in the parent POM. Previous version failed fosstar test.

fix: Update json version in parent POM

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/prepare-release.yaml

AI/ai-sdk-java-backlog#187
Added note to PR checklist for release process. Updated [GitHub Releases notes](https://github.com/SAP/ai-sdk-java/releases) for v1.0.0 and 1.2.0.

chore: Improve release notes 

---

pom.xml

`mvn install` should fail as fast as possible regardless of what step fails.

chore: DevOps `mvn install` fail early

---

docs/release-notes/release-notes-0-to-14.md
docs/release-notes/release_notes.md

Switch to absolute URL for release notes, which will be used somewhere else like GH release.

chore: Use absolute URL in release notes

---

docs/guides/ORCHESTRATION_CHAT_COMPLETION.md
docs/release-notes/release_notes.md
orchestration/src/main/java/com/sap/ai/sdk/orchestration/ConfigToRequestTransformer.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/OrchestrationUnitTest.java
orchestration/src/test/resources/__files/jsonObjectResponse.json
orchestration/src/test/resources/__files/jsonSchemaResponse.json
orchestration/src/test/resources/__files/responseFormatTextResponse.json
orchestration/src/test/resources/jsonObjectRequest.json
orchestration/src/test/resources/jsonSchemaRequest.json
orchestration/src/test/resources/responseFormatTextRequest.json
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/OrchestrationService.java
sample-code/spring-app/src/main/resources/static/index.html
sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java

AI/ai-sdk-java-backlog#162.
This PR enables and tests using the `response_format` option for chat completion. There are 3 options:
- `JSON_OBJECT` tells the AI to respond in JSON format (without giving the explicit structure)
- `JSON_SCHEMA` tells the AI to respond with JSON that adheres to a given JSON schema
- `TEXT` tells the AI to respond in plain text
Note, that this PR does not cover convenience API. Convenience API for JSON schema is split into a new issue AI/ai-sdk-java-backlog#195.

feat: [Orchestration] Enable and test setting `response_format`

---

docs/release-notes/release_notes.md
orchestration/src/main/java/com/sap/ai/sdk/orchestration/SystemMessage.java
orchestration/src/main/java/com/sap/ai/sdk/orchestration/UserMessage.java

Before, the constructors for `SystemMessage` and `UserMessage` using a `MessageContent` object where public unintentionally. This PR hides them.

fix: [Orchestration] Hide constructors for System- and UserMessage

---

pom.xml

The dependency vulnerability scan failed because of a bug. It was [fixed in 12.1.0](https://github.com/jeremylong/DependencyCheck/blob/main/CHANGELOG.md#version-1210-2025-02-16)
[Successful run](https://github.com/SAP/ai-sdk-java/actions/runs/13365340902)

fix: [DevOps] Dependency vulnerability scan to 12.1.0

---

orchestration/pom.xml
orchestration/src/test/java/com/sap/ai/sdk/orchestration/spring/ImportCheckTest.java
pom.xml

AI/ai-sdk-java-backlog#180.
Currently, we might by accident use Spring AI within any Orchestration class without noticing.
Using Spring AI within any class not under a .spring package should lead to a compile or test or e2e test failure.

chore: [DevOps] enforce Spring AI optional

---

README.md

AI/ai-sdk-java-backlog#197.
The sample code did not explain how to use the destination in our clients

chore: better header documentation

---

sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/ScenarioTest.java

AI/ai-sdk-java-backlog#206 (related)
This PR disables the `openAiModelAvailability` test since the list of models on canary and prod are not identical.

fix: Disable test regarding model availability

---

foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiChatCompletionRequest.java
foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiToolChoice.java
foundation-models/openai/src/test/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiChatCompletionRequestTest.java
foundation-models/openai/src/test/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiClientGeneratedTest.java
sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/services/OpenAiServiceV2.java

Follow up https://github.com/SAP/ai-sdk-java/pull/330#discussion_r1971179098
Please provide a short description of what your change does and why it is needed.

chore: Consolidate OpenAI convenience methods to set tool-choice

---

foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiToolChoice.java

AI/ai-sdk-java-backlog#203.
Add `@Beta` tag on new convenience and `equals` and `hashCode` for comparison sake.

chore: [OpenAI] Beta tag on toolChoice conv with equals and hashcode

---

docs/release-notes/release_notes.md

Align release notes with JS SDK.

fix: Align release notes with JS SDK

---

foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiError.java
orchestration/pom.xml
orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationError.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/OrchestrationUnitTest.java
orchestration/src/test/resources/__files/error500Response.json

The exception for server errors is currently not helpful. The location can be used for a better message:
```diff
-Request failed with status 500 Internal Server Error and error message: 'Internal Server Error'
+Request failed with status 500 Internal Server Error and error message: 'Internal Server Error located in Masking Module - Masking'
```

fix: [Orchestration] Added location to server errors

---

docs/guides/ORCHESTRATION_CHAT_COMPLETION.md

This is a small addition to the docs on how to set a response format. It makes it clear that the `@JsonProperty(required = true)` is necessary in classes we use as the base for JSON schema generation.

docs: Update docs on setting response-format

---

sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/GroundingTest.java

It's been over a week since I reported the issue.
Grounding team does not seem to be capable to fix it in timely manner.
We'd appreciate being able to release again. Therefore, let's disable the failing test. Until they figured it out.
Created follow-up here:
https://github.com/SAP/ai-sdk-java-backlog/issues/232

chore: (Grounding) Disable failing E2E test

---

sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/PromptRegistryTest.java

Before, the `history()` test of `PromptRegistryTest` in the e2e tests was very flaky because the deletion often takes a few moments to actually work. This is to make sure our tests do not fail because of this.

chore: Improve Prompt Registry History test

---

sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/PromptRegistryTest.java

The fix in https://github.com/SAP/ai-sdk-java/pull/411 was not correct. When trying to avoid flakyness in the history test, I changed it from `= 2` to `>2` in that PR, but it should be `>=2`.

chore: Fix the prompt registry history test

---

docs/release_notes.md
orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationAiModel.java

AI/ai-sdk-java-backlog#258.
When using new models like Claude 3.7, Gemini 2.0 Flash and Flash Lite , auto completion won't work.

feat: [Orchestration] Added Gemini 2.0 models

---

docs/release_notes.md
orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationChatResponse.java
orchestration/src/test/java/com/sap/ai/sdk/orchestration/OrchestrationUnitTest.java
orchestration/src/test/resources/__files/errorJsonSchemaResponse.json
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/OrchestrationService.java
sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java

AI/ai-sdk-java-backlog#254.
Currently, users have to manually parse a string as JSON into their class. Users can now let the AI SDK do the parsing.

feat: [Orchestration] Added support for transforming a JSON output in to an entity

---

docs/release_notes.md
orchestration/src/main/java/com/sap/ai/sdk/orchestration/JacksonMixins.java
sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java

AI/ai-sdk-java-backlog#278.
Fixes #474 
Fixed duplicate properties, Anthropic Claude chat completions are now working.
⚠️This is only manually e2e tested since verify does not check for duplicate **equal** `key:values`

fix: [Orchestration] duplicated properties

---

core-services/document-grounding/pom.xml
core-services/prompt-registry/pom.xml
core/pom.xml
foundation-models/openai/pom.xml
orchestration/pom.xml
pom.xml

SCM information is now mandatory to include in pom files so that maven central validates the modules during deployment.

fix: Add scm information (now required by maven central)

---

sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/ScenarioTest.java

See here for follow-up:
https://github.com/SAP/ai-sdk-java-backlog/issues/306

chore: [OpenAI] Temporarily disable failing OpenAi model integration test

---

pom.xml

This is not used
- [see Cloud SDK `distributionManagement`](https://github.com/SAP/cloud-sdk-java/blob/bd6e1f94dc902b6becb25ba313349fb2179fa30a/pom.xml#L44)
- [Also see AI SDK server id defined in `sonatype publish plugin`](https://github.com/SAP/ai-sdk-java/blob/e366acb2bccb8b5db9bed006f7179a04606e6154/pom.xml#L927)

fix: [DevOps] remove distributionManagement sonatype

---

.github/workflows/spec-update.yaml

The action is being called a lot more by different repositories, while it is only called if the branch changes the spec file, it might not be changed on every commit, thus we can save time and finish early

chore: [DevOps] succeed early if spec is unchanged

---

.github/workflows/cache-maven-dependencies.yaml
.github/workflows/continuous-integration.yaml
.github/workflows/spec-update.yaml

AI/ai-sdk-java-backlog#219.
Some errors can appear if we run maven commands without cache too many times

chore: [DevOps] Added Maven cache

---

README.md

https://github.com/SAP/ai-sdk-java/issues/569
Simply additing clarification on the purpose of these frameworks listen in our README.md so users don't expect documentation along with.

docs: Clarify optionality of frameworks in README

---

docs/release_notes.md
orchestration/src/main/java/com/sap/ai/sdk/orchestration/OrchestrationAiModel.java
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/SpringAiAgenticWorkflowService.java
sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/services/SpringAiOrchestrationService.java

AI/ai-sdk-java-backlog#324.
Models are updated

feat: [Orchestration] Added MistralAI model
